steps:

# ----------------------------------------
# Prep Work
# (0) Prepare the venv and install the public stable version of the lib off of PyPI
# (1) establish GitHub App auth via the init of the checks lib
# (2) use this auth'd session to pull the to-be-checked revision
# (3) reinstall and reinit the checks lib at that revision, thus making the to-be-checked code check itself
# You would probably want to do (0)-(2) similarly for your own repos, just skipping (3)
# ----------------------------------------

  # 0. Set up Python environment
  - name: 'python:3.11'
    id: 'init-venv'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python3 -m venv /workspace/venv
        source /workspace/venv/bin/activate
        python3 -m pip install .  # todo: repace with install from pypi once deps are ok

  # 1. Initialize checks lib to establish GitHub App auth
  - name: 'python:3.11'
    id: 'init-checks-lib'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$_GH_PRIVATE_KEY_PEM_FILE" > "$_GH_PRIVATE_KEY_PATH"
        source /workspace/venv/bin/activate

        python3 -m github_checks.cli init --print-gh-app-install-token > GH_APP_TOKEN.txt
    env:
      - 'GH_APP_ID=$_GH_APP_ID'
      - 'GH_APP_INSTALL_ID=$_GH_APP_INSTALL_ID'
      - 'GH_REPO_BASE_URL=https://$_GH_REPO_BASE'
      - 'GH_PRIVATE_KEY_PEM=$_GH_PRIVATE_KEY_PATH'
      - 'GH_PICKLE_FILEPATH=$_GH_PICKLE_FILEPATH'
    secretEnv: ['_GH_PRIVATE_KEY_PEM_FILE']

  # 2. check out the to-be-checked revision
  - name: 'gcr.io/cloud-builders/git'
    id: 'checkout-commit-to-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TOKEN="$(tr -d '\n' < /workspace/GH_APP_TOKEN.txt)"
        rm /workspace/GH_APP_TOKEN.txt  # clean up the secret to limit leakage risk

        # since we run on ourselves, we already have a shallow clone of the repo in our CWD
        # we need to unshallow it to access other commits than the build's head commit
        # usually, you'd just clone the repo from scratch here
        git config --global advice.detachedHead false
        git config --global safe.directory /workspace
        git remote set-url origin "https://git:$$TOKEN@${_GH_REPO_BASE}.git"
        git fetch --unshallow

        git checkout "$_GH_COMMIT_SHA"

  # 3. Reinstall and reinit the checks lib at the to-be-checked revision
  # This is to make sure we're running the to-be-checked code to check itself, giving us
  # a 2-in-1 validation of the code being both clean and working as intended in one build.
  # This step is unnecessary for other repos, you'd just continue with the PyPi version.
  - name: 'python:3.11'
    id: 'reinit-checks-lib'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python3 -m github_checks.cli cleanup
        python3 -m pip uninstall -y github-checks

        python3 -m pip install .
        python3 -m github_checks.cli init
    env:
      - 'GH_APP_ID=$_GH_APP_ID'
      - 'GH_APP_INSTALL_ID=$_GH_APP_INSTALL_ID'
      - 'GH_REPO_BASE_URL=https://$_GH_REPO_BASE'
      - 'GH_PRIVATE_KEY_PEM=$_GH_PRIVATE_KEY_PATH'
      - 'GH_PICKLE_FILEPATH=$_GH_PICKLE_FILEPATH'

# ----------------------------------------
# Actual work to check the repo's contents starts here
# ----------------------------------------

  # 0. install any dependencies we'll need for this repo's tests
  - name: 'python:3.11'
    id: 'install-deps'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python3 -m pip install --no-input -r tests/requirements_qa.txt

  # 1. run ruff on ourselves
  - name: 'python:3.11'
    id: 'ruff-checks'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python3 -m github_checks.cli start-check-run --check-name ruff-checks
        ruff check . --output-format=json > ruff_output.json
        python3 -m github_checks.cli finish-check-run ruff_output.json --log-format ruff-json -i .checksignore
    env:
      - 'GH_LOCAL_REPO_PATH=$_GH_LOCAL_REPO_PATH'
      - 'GH_CHECK_REVISION=$_GH_COMMIT_SHA'
      - 'GH_PICKLE_FILEPATH=$_GH_PICKLE_FILEPATH'

  # 2. run mypy on ourselves
  - name: 'python:3.11'
    id: 'mypy-checks'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python3 -m github_checks.cli start-check-run --check-name mypy-checks
        mypy . --output=json > mypy_output.json
        python3 -m github_checks.cli finish-check-run mypy_output.json --log-format mypy-json -i .checksignore
    env:
      - 'GH_LOCAL_REPO_PATH=$_GH_LOCAL_REPO_PATH'
      - 'GH_CHECK_REVISION=$_GH_COMMIT_SHA'
      - 'GH_PICKLE_FILEPATH=$_GH_PICKLE_FILEPATH'

  # 3. run pyright on ourselves
  - name: 'python:3.11'
    id: 'pyright-checks'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python3 -m github_checks.cli start-check-run --check-name pyright-checks
        pyright . --outputjson > pyright_output.json
        python3 -m github_checks.cli finish-check-run pyright_output.json --log-format pyright-json -i .checksignore
    env:
      - 'GH_LOCAL_REPO_PATH=$_GH_LOCAL_REPO_PATH'
      - 'GH_CHECK_REVISION=$_GH_COMMIT_SHA'
      - 'GH_PICKLE_FILEPATH=$_GH_PICKLE_FILEPATH'

  # 4. run pytest as a raw check until we have support for --json-report/--json-report-file
  - name: 'python:3.11'
    id: 'pytest-checks-raw'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python3 -m github_checks.cli start-check-run --check-name pytest-checks-raw
        pytest --md-report --md-report-flavor gfm . > pytest_raw_output.txt
        CONCLUSION=$([[ $$? -eq 0 ]] && echo "success" || echo "action_required")
        python3 -m github_checks.cli finish-check-run pytest_raw_output.txt --conclusion $$CONCLUSION --log-format raw
    env:
      - 'GH_LOCAL_REPO_PATH=$_GH_LOCAL_REPO_PATH'
      - 'GH_CHECK_REVISION=$_GH_COMMIT_SHA'
      - 'GH_PICKLE_FILEPATH=$_GH_PICKLE_FILEPATH'

  # 5. upload pytest coverage as a neutral-conclusion check
  - name: 'python:3.11'
    id: 'pytest-coverage-report'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python3 -m github_checks.cli start-check-run --check-name pytest-coverage-report
        pytest --cov-report markdown:cov.txt --cov=github_checks tests/
        python3 -m github_checks.cli finish-check-run cov.txt --conclusion neutral --log-format raw
    env:
      - 'GH_LOCAL_REPO_PATH=$_GH_LOCAL_REPO_PATH'
      - 'GH_CHECK_REVISION=$_GH_COMMIT_SHA'
      - 'GH_PICKLE_FILEPATH=$_GH_PICKLE_FILEPATH'
  
  # 6. run bandit as a raw check until we have support for its -f json option
  - name: 'python:3.11'
    id: 'bandit-checks-raw'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python3 -m github_checks.cli start-check-run --check-name bandit-checks-raw
        bandit -r . -x "./tests/","./venv/" > bandit_raw_output.txt
        CONCLUSION=$([[ $$? -eq 0 ]] && echo "success" || echo "action_required")
        cat $$CONCLUSION
        python3 -m github_checks.cli finish-check-run bandit_raw_output.txt --conclusion $$CONCLUSION --log-format raw
    env:
      - 'GH_LOCAL_REPO_PATH=$_GH_LOCAL_REPO_PATH'
      - 'GH_CHECK_REVISION=$_GH_COMMIT_SHA'
      - 'GH_PICKLE_FILEPATH=$_GH_PICKLE_FILEPATH'

  # 7. run the jsonschema checks on an example file for testing
  - name: 'python:3.11'
    id: 'jsonschema-checks'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python3 -m github_checks.cli start-check-run --check-name test-jsonschema-checks
        check-jsonschema -o json --schemafile tests/json_validation/user.schema.json tests/json_validation/valid_user.json > jsonschema_output.json
        python3 -m github_checks.cli finish-check-run jsonschema_output.json --log-format check-jsonschema
    env:
      - 'GH_LOCAL_REPO_PATH=$_GH_LOCAL_REPO_PATH'
      - 'GH_CHECK_REVISION=$_GH_COMMIT_SHA'
      - 'GH_PICKLE_FILEPATH=$_GH_PICKLE_FILEPATH'

  # 8. run the sarif checks on ourselves via ruff
  - name: 'python:3.11'
    id: 'sarif-ruff-checks'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python3 -m github_checks.cli start-check-run --check-name sarif-ruff-checks
        ruff check . --output-format=sarif > sarif_output.json
        python3 -m github_checks.cli finish-check-run sarif_output.json --log-format sarif -i .checksignore
    env:
      - 'GH_LOCAL_REPO_PATH=$_GH_LOCAL_REPO_PATH'
      - 'GH_CHECK_REVISION=$_GH_COMMIT_SHA'
      - 'GH_PICKLE_FILEPATH=$_GH_PICKLE_FILEPATH'

timeout: '900s'
substitutions:
  _GH_APP_ID: "1065841"
  _GH_APP_INSTALL_ID: "57443831"
  _GH_REPO_BASE: "github.com/jgubler/github-checks"
  _GH_PRIVATE_KEY_PATH: /workspace/github_app_private_key.pem
  _GH_PICKLE_FILEPATH: /workspace/github_checks_session.pkl
  _GH_LOCAL_REPO_PATH: /workspace/

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/demo-github-checks-app-pem/versions/latest
      env: _GH_PRIVATE_KEY_PEM_FILE
options:
  logging: CLOUD_LOGGING_ONLY
